FROM php:8.1-fpm

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    zip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    curl \
    nodejs npm \
    && docker-php-ext-install pdo_mysql zip mbstring exif pcntl bcmath gd

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy project files
COPY . .

# Pastikan folder storage dan bootstrap/cache ada
RUN mkdir -p storage/framework/views storage/framework/cache storage/logs bootstrap/cache

# Install PHP dependencies tanpa dev dan optimize autoloader
RUN composer install --no-dev --optimize-autoloader

# Install npm packages & build frontend
RUN npm install && npm run prod

# Cache config, routes, views supaya lebih cepat
RUN php artisan config:cache && php artisan route:cache && php artisan view:cache

# Set permission supaya www-data bisa tulis di storage dan bootstrap/cache
RUN chown -R www-data:www-data storage bootstrap/cache \
    && chmod -R 775 storage bootstrap/cache

# Expose port 9000 (php-fpm)
EXPOSE 9000

# Start php-fpm server
CMD ["php-fpm"]
